
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 972aeedccf61d7d2b1b38459f580da05
            client-secret: bxWOsVdaYMQZGJhUEZI8AeUsS0pdjmmV
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
          google:
            client-id: 367973055587-fe62h05ngtoeqfie2q47uj8facuvurck.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id